name: Build Tauri App

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner to build .exe

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust to your Node.js version

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal

    - name: Install dependencies
      run: npm ci  # or yarn install

    - name: Build Tauri app
      run: npm run tauri build  # Adjust if your build command is different

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: tauri-app
        path: src-tauri/target/release/bundle/msi/*.msi  # Adjust path if necessary